<Project>
  <PropertyGroup>
    <Authors>Jonny Muir</Authors>
    <Company>Jonny Muir</Company>
    <VersionPrefix>0.4.0</VersionPrefix>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
